### ISSUE TITLE
package missing during build

### ISSUE THREAD

**Issue by trogeat** [knobik/rpicloud#2]
```
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /home/rpi/.node-gyp/12.18.3
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/web/node_modules/node-gyp/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/web/node_modules/node-gyp/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/web/node_modules/node-gyp/node_modules/which/which.js:80:29)
gyp ERR! stack     at /web/node_modules/node-gyp/node_modules/which/which.js:89:16
gyp ERR! stack     at /web/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /web/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
gyp ERR! System Linux 5.4.51-v7l+
gyp ERR! command "/usr/bin/node" "/web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /web/node_modules/node-sass
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rpi/.npm/_logs/2020-07-28T17_31_35_685Z-debug.log
Done!
```
fix : apt install make 
package was missing to build module

**Comment by knobik** [comment]
Could not replicate, does this problem still exist?

**Comment by knobik** [comment]
fixed by adding build-essential to Dockerfile.
